#!/bin/bash

#set -x

SYSOUT_PATH="/home/nc/notecards/NOTECARDS.SYSOUT"
VMEM_PATH="/home/nc/vmem/lisp.virtualmem"

if [ $# -gt 0 ]; then
	if [ "$1" == "new" ]; then
		sysout=${SYSOUT_PATH}
	else
		if [ -f ${VMEM_PATH} ]; then
			sysout=""
		else 
			sysout=${SYSOUT_PATH}
		fi
	fi
else
	sysout=${SYSOUT_PATH}
fi

if [ $# -gt 1 ]; then
	width=$2
else
	width=1024
fi

if [ $# -gt 2 ]; then
	height=$3
else
	height=808
fi
su nc <<EOF
#set -x
cd /app/medley
/usr/bin/websockify --daemon ${PORT} localhost:1${PORT}
/usr/bin/Xvnc -geometry ${width}x${height} -rfbport 1${PORT} -nolisten tcp -localhost -nevershared -dontdisconnect :0 &
export DISPLAY=:0
for i in {1..10}
    do
        xdpyinfo > /dev/null
        if [ $? -eq 0 ]; 
            then
                break
            else
                sleep 1
        fi
    done
#xmodmap -e "keycode 12 = Alt_L" -e "keycode 13 = Alt_R" -e "keycode 14 = Meta_L" -e "keycode 15 = Meta_R"
xmodmap -e "keycode 12 =" -e "keycode 13 ="
PATH="/app/maiko:$PATH" ./run-medley -g ${width}x${height} -sc ${width}x${height} -vmem ${VMEM_PATH} ${sysout}
EOF
